export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_BUSES_START = "FETCH_BUSES_START";
export const FETCH_BUSES_SUCCESS = "FETCH_BUSES_SUCCESS";
export const FETCH_BUSES_FAILURE = "FETCH_BUSES_FAILURE";